#include "../GlobalDefines.cginc"

#ifndef DX11
    #pragma use_dxc
    // #pragma enable_d3d11_debug_symbols
#endif
#include "CommonData.cginc"
#include "Materials.cginc"

Texture2D<float2> MotionVectors;


#ifdef HardwareRT
    #include "UnityRayQuery.cginc"
    #pragma require inlineraytracing
    RaytracingAccelerationStructure myAccelerationStructure;
#endif
#ifdef ReSTIRAdvancedValidation
inline float VisabilityCheck(SmallerRay ray, float dist) {
#else 
inline bool VisabilityCheck(SmallerRay ray, float dist) {
#endif
    #ifdef HardwareRT
        const uint rayFlags = RAY_FLAG_FORCE_OPAQUE  ;
        UnityRayQuery<rayFlags> q;
        RayDesc myRay;
        myRay.Origin = ray.origin;
        myRay.Direction = ray.direction;
        myRay.TMin = 0;
        myRay.TMax = dist;
        while(true) {
            q.TraceRayInline(myAccelerationStructure, rayFlags, 0xff, myRay);
            while(q.Proceed()){}
            
            if(q.CommittedStatus() == COMMITTED_TRIANGLE_HIT) {

                    float u = q.CommittedTriangleBarycentrics().y;
                    float v = q.CommittedTriangleBarycentrics().x;
                    int2 Indexes = int2(q.CommittedInstanceID(), q.CommittedGeometryIndex());
                    int triangle_id = q.CommittedPrimitiveIndex();
                    #if defined(IgnoreBackfacing) || defined(AdvancedAlphaMapped) || defined(IgnoreGlassShadow) || defined(AdvancedBackground)
                        int triangleOffset = SubMeshOffsets[MeshOffsets[Indexes.x].x + Indexes.y];
                        triangle_id += triangleOffset;
                        int mesh_id = MeshOffsets[Indexes.x].y;
                        int MaterialIndex = (_MeshData[mesh_id].MaterialOffset + AggTrisA[triangle_id].MatDat);
                        if(GetFlag(_Materials[MaterialIndex].Tag, IsBackground) || GetFlag(_Materials[MaterialIndex].Tag, ShadowCaster))  {myRay.TMin = q.CommittedRayT() + NormalOffset; continue;} 
                    #endif
                    #ifdef AdvancedAlphaMapped
                        if(_Materials[MaterialIndex].MatType == CutoutIndex) {
                            float2 BaseUv = TOHALF(AggTrisA[triangle_id].tex0) * (1.0f - u - v) + TOHALF(AggTrisA[triangle_id].texedge1) * u + TOHALF(AggTrisA[triangle_id].texedge2) * v;
                            if(_Materials[MaterialIndex].AlphaTex.x > 0)
                                if(SampleTexture(BaseUv, SampleAlpha, _Materials[MaterialIndex]).x < _Materials[MaterialIndex].AlphaCutoff) {myRay.TMin = q.CommittedRayT() + NormalOffset; continue;}
                        }
                    #endif
                    #ifdef IgnoreBackfacing
                        TrianglePos tri = triangle_get_positions(triangle_id);
                        if(_Materials[MaterialIndex].specTrans != 1 && dot(normalize(cross(normalize(tri.posedge1), normalize(tri.posedge2))), mul((float3x3)_MeshData[mesh_id].W2L, ray.direction)) <= 0) {myRay.TMin = q.CommittedRayT() + NormalOffset; continue;}
                    #endif
                    #ifdef IgnoreGlassShadow
                        if(_Materials[MaterialIndex].specTrans == 1) {
                            myRay.TMin = q.CommittedRayT() + NormalOffset; 
                            continue;
                        }
                    #endif


        #ifdef ReSTIRAdvancedValidation
                return q.CommittedRayT();
            }
            return dist;
        #else
                return false;
            }
            return true;
        #endif
        }
    #else
#ifdef ReSTIRAdvancedValidation
    VisabilityCheckCompute(ray, dist);
    return dist;
#else
    return VisabilityCheckCompute(ray, dist);
#endif
    #endif
}

#pragma kernel ReSTIRGIKernel




float IndirectBoost;
bool UseReSTIRGITemporal;
bool UseReSTIRGISpatial;
bool DoReSTIRGIConnectionValidation;
int ReSTIRGITemporalMCap;

struct RadianceData {
    float3 Color;
    float Wsum;
    float M;
    float W;
};

struct RayData2 {
    uint ReservoirAge;
    uint PixelIndex;
};

struct ReservoirStruct {
    RadianceData Radiance;
    // RayData2 Ray;
};

inline uint2 PackRadianceData(RadianceData Radiance) {
    uint W = f32tof16(Radiance.W);      
    uint M = f32tof16(Radiance.M);      
    uint PackedMW = (W << 16) | (M << 0);
    uint PackedColor = packRGBE(Radiance.Color);
    
    return uint2(PackedColor, PackedMW);
}


inline void UnpackRadianceData(uint2 RadianceDataPacked, float3 Diffuse, inout RadianceData Radiance) {
    Radiance.Color = unpackRGBE(RadianceDataPacked.x);
    Radiance.W = f16tof32(RadianceDataPacked.y >> 16);
    Radiance.M = f16tof32(RadianceDataPacked.y >> 0);
    Radiance.Wsum = Radiance.W * Radiance.M * luminance(Radiance.Color * Diffuse);
}


// ------------------------ RESERVOIRStruct PACKING FUNCTIONS-----------------------


inline uint2 PackRayData(RayData2 Ray)
{
    return uint2(Ray.ReservoirAge, Ray.PixelIndex);
}








inline bool ReservoirUpdate(RadianceData CandidateRadiance, inout ReservoirStruct Reservoir, float Random) {
    Reservoir.Radiance.Wsum += CandidateRadiance.Wsum;
    Reservoir.Radiance.M += CandidateRadiance.M;
    
    if (Random * Reservoir.Radiance.Wsum <= CandidateRadiance.Wsum) {   
        Reservoir.Radiance.Color = CandidateRadiance.Color;
        return true;
    }
    
    return false;
}


inline bool ReservoirMergeCandidates(ReservoirStruct SourceReservoir, float SampleWeight, float3 Diffuse, float Random, inout ReservoirStruct TargetReservoir) {
   

    SourceReservoir.Radiance.Wsum *= SampleWeight;
    SourceReservoir.Radiance.M *= SampleWeight;
    
    return ReservoirUpdate(SourceReservoir.Radiance, TargetReservoir, Random);
}

// Merges central reservoirStruct with a temporal neighbour (Radiance & Ray datas are exhanged) loaded externally
inline bool ReservoirMerge(uint2 SampleReservoirPacked, float SampleWeight, float3 Diffuse, float Random, inout ReservoirStruct TargetReservoir, float MISWeight = 1) {
    RadianceData SampleRadiance;
   
    UnpackRadianceData(SampleReservoirPacked.xy, Diffuse, SampleRadiance);
    SampleRadiance.M *= SampleWeight;
    SampleRadiance.Wsum *= SampleWeight * MISWeight;
    
    return ReservoirUpdate(SampleRadiance, TargetReservoir, Random);
}

// Empty RadianceData initialization
inline void RadianceDataInitialize(out RadianceData Radiance) {
    Radiance.Color = 0;
    Radiance.Wsum = 0;
    Radiance.M = 0;
    Radiance.W = 0;
}

inline void RayDataInitialize(out RayData2 Ray) {
    Ray.ReservoirAge = 0;
}


// Empty reservoirStruct initialization
inline void ReservoirInitialize(out ReservoirStruct ReservoirStruct) {
    RadianceDataInitialize(ReservoirStruct.Radiance);
    // RayDataInitialize(ReservoirStruct.Ray);
}


Texture2D<uint2> BackupReservoir;
Texture2D<uint4> BackupReservoirWorldPos;

Texture2D<half> Gradient;
RWTexture2D<half> GradientWrite;
#define KernelSize 8
[numthreads(KernelSize, KernelSize, 1)]
void ReSTIRGIKernel(uint3 id : SV_DispatchThreadID, uint3 id2 : SV_GroupThreadID, uint3 id3 : SV_GroupID, uint id4 : SV_GroupIndex) {
    if(id.x >= screen_width || id.y >= screen_height) return;
    const int pixel_index = id.x + id.y * screen_width;

    const float2 UV = id.xy / float2(screen_width, screen_height);
    SmallerRay CameraRay = CreateCameraRay(id.xy / float2(screen_width, screen_height) * 2.0f - 1.0f);
    [branch]if(DoPanorama) {
        float2 jitter = ((random(0, pixel_index) - 0.5));
        if(OIDNGuideWrite) jitter = 0;
        float2 uv = float2((id.xy + jitter) / float2(screen_width, screen_height));
        uv.y = 1.0f - uv.y;
        uv.x = (uv.x * (Segment.y - Segment.x)) + Segment.x;
        uv.x = 1.0f - uv.x;

        CameraRay = CreateRay(mul(CamToWorld, float4(0.0f, 0.0f, 0.0f, 1.0f)).xyz + NearPlane * normalize(equirectUvToDirection(uv)), normalize(equirectUvToDirection(uv)));
    }


    const float4 GBuffer = ScreenSpaceInfoRead[id.xy];
    const int MatIndex = (asuint(GBuffer.w) << 4) >> 4;
    const uint Case = (asuint(GBuffer.w) << 1) >> 30;
    float3 GeomNorm = i_octahedral_32(asuint(GBuffer.x));
    const float3 SurfNorm = i_octahedral_32(asuint(GBuffer.y));
    float3 PrimaryHitPosition = LoadSurfaceInfo(id.xy);

    const ColData CenterCol = GlobalColors[pixel_index];
    MaterialData SurfaceMat = _Materials[MatIndex];
    uint Flag = CenterCol.Flags;
    SurfaceMat.surfaceColor = max(unpackRGBE(Flag), 0.005f);
    uint MetRoughIsSpec = CenterCol.MetRoughIsSpec;
    SurfaceMat.roughness = FromColorSpecPacked(MetRoughIsSpec).y;
    SurfaceMat.metallic = FromColorSpecPacked(MetRoughIsSpec).x;


    uint4 RunningWorldPos;

    float3 bsdf = 0;
    float pdf = 0;



    ReservoirStruct SecondaryReservoir;
    ReservoirInitialize(SecondaryReservoir);

    uint4 SecondarySurfacePos = ReSTIRSecondaryDestinationWorldPos[id.xy];

    float3 SecondaryWorldPos =  LoadSurfaceInfo23(SecondarySurfacePos, PrimaryHitPosition);
    bool ValidSecondary =       any(SecondarySurfacePos != 0);
    if(ValidSecondary) {
        ValidSecondary = ValidSecondary &&     EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(SecondaryWorldPos - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);

        SecondaryReservoir.Radiance.Color = (CenterCol.Indirect * IndirectBoost + CenterCol.Direct);
        SecondaryReservoir.Radiance.Wsum = luminance(SecondaryReservoir.Radiance.Color * CenterCol.Data.xyz);
        SecondaryReservoir.Radiance.M = 1;
    }



//----------------------


    ReservoirStruct NEEReservoir;
    ReservoirInitialize(NEEReservoir);

    uint4 NEESurfacePos = NEEDestinationWorldPos[id.xy];

    float3 NEEWorldPos =        LoadSurfaceInfo23(NEEDestinationWorldPos[id.xy], PrimaryHitPosition);
    bool ValidNEE =             any(NEESurfacePos != 0);
    if(ValidNEE) {
        ValidNEE = ValidNEE &&     EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(NEEWorldPos - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);
        NEEReservoir.Radiance.Color = pow(unpackRGBE(CenterCol.PrimaryNEERay),2.2f);
        NEEReservoir.Radiance.Wsum = luminance(NEEReservoir.Radiance.Color * bsdf);
        NEEReservoir.Radiance.M = 1;
    }

//-----------------------------


    ReservoirStruct UnifiedReservoir;
    ReservoirInitialize(UnifiedReservoir);
    float3 UnifiedWorldPos = float3(0,0,0);

    [branch]if(ValidSecondary ^ ValidNEE) {
        [branch]if(ValidSecondary) {
            UnifiedReservoir = SecondaryReservoir;
            // UnifiedReservoir.Ray.ReservoirAge = 1;
            UnifiedWorldPos = SecondaryWorldPos;
            RunningWorldPos = SecondarySurfacePos;
        } else {
            UnifiedReservoir = NEEReservoir;
            // UnifiedReservoir.Ray.ReservoirAge = 2;
            UnifiedWorldPos = NEEWorldPos;
            RunningWorldPos = NEESurfacePos;
        }
    } else if(ValidSecondary && ValidNEE) {
            bool MergedInSource = ReservoirMergeCandidates(SecondaryReservoir, 1, float3(1,1,1), randomNEE(128, pixel_index).x, NEEReservoir);
            UnifiedReservoir = NEEReservoir;
            UnifiedWorldPos = MergedInSource ? SecondaryWorldPos : NEEWorldPos;
            RunningWorldPos = MergedInSource ? SecondarySurfacePos : NEESurfacePos;
    }

    UnifiedReservoir.Radiance.M = 1;
    EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPos - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);
    UnifiedReservoir.Radiance.W = clamp(UnifiedReservoir.Radiance.Wsum / max(max(UnifiedReservoir.Radiance.M, 1) * luminance(UnifiedReservoir.Radiance.Color * bsdf), 1e-7), 0, 102222000.0f);




    float2 MotionVector = MotionVectors[UV * float2(screen_width, screen_height)];//.SampleLevel(my_linear_clamp_sampler, UV, 0).xy;
    int2 prevIndex = int2(floor(((float2(id.xy) + 0.5) * float2(rcp(screen_width), rcp(screen_height)) - MotionVector) * float2(screen_width, screen_height)));
  

    [branch]if(!(any(prevIndex >= int2(screen_width, screen_height) || prevIndex < 0)) && !(Case == 0 && SurfaceMat.roughness < 0.05) && UseReSTIRGITemporal) {
        float4 PrevGBuffer = PrevScreenSpaceInfo[prevIndex];
        float NormDiff = max(dot(GeomNorm, i_octahedral_32(asuint(PrevGBuffer.x))), 0);
        float s = sqrt(0.05 * dot(CamPos - PrimaryHitPosition, CamPos - PrimaryHitPosition) / PI);
        float h_p = exp(-(length(PrimaryHitPosition - LoadSurfaceInfoPrevInCurrent(prevIndex))) / s);
        float h_n = pow(NormDiff, 8);
        float h = h_p * h_n;
        float NormDiff2 = pow(max(dot(SurfNorm, i_octahedral_32(asuint(PrevGBuffer.y))), 0),8);

        [branch]if(h >= 0.5f && NormDiff2 >= 0.1f) {
            uint4 TemporalSurface = ReservoirUnifiedDestinationWorldPosTemporalPrevious[prevIndex];
            float3 TemporalPosition = LoadSurfaceInfo23(TemporalSurface, PrimaryHitPosition);
            bool ValidTemporal = EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(TemporalPosition - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);
            [branch]if(ValidTemporal) {
                #ifdef ReSTIRAdaptiveLighting
                    #ifdef ReSTIRAdvancedValidation
                        if(DoReSTIRGIConnectionValidation) {
       
                            #ifdef ExpensiveAdaptiveTemporal
                                ReservoirStruct TemporalReservoir;
                                ReservoirInitialize(TemporalReservoir);
                                UnpackRadianceData(ReservoirB[prevIndex], 1.0f, TemporalReservoir.Radiance);

                                if(SurfaceMat.specTrans == 0) {
                                    float3 TempPos = TemporalPosition;
                                    SmallerRay ray = CreateRay(PrimaryHitPosition, normalize(TemporalPosition - PrimaryHitPosition));
                                    bool FlippedGeomnorm = (SurfaceMat.diffTrans != 0 && dot(ray.direction, GeomNorm) <= 0);
                                    if(FlippedGeomnorm) GeomNorm *= -1.0f;
                                    PrimaryHitPosition += GeomNorm * NormalOffset;
                                    ray = CreateRay(PrimaryHitPosition, normalize(TemporalPosition - PrimaryHitPosition));

                                    float Distance = length(PrimaryHitPosition - TemporalPosition) - 0.025f;
                                    [branch]if (luminance(TemporalReservoir.Radiance.Color) != 0) {
                                        if(dot(ray.direction, GeomNorm) <= 0) {
                                                h = 0;
                                        } else {
                                        #ifdef ReSTIRAdvancedValidation
                                            float TargDist = VisabilityCheck(ray, Distance);
                                            if (TargDist != Distance)
                                        #else
                                            if(!VisabilityCheck(ray, Distance))
                                        #endif
                                                h = 0;
                                        }
                                    }
                                    PrimaryHitPosition -= GeomNorm * NormalOffset;
                                    if(FlippedGeomnorm) GeomNorm *= -1.0f;
                                }


                            #else
                            h *= saturate(Gradient[prevIndex]) > 0.0f;
                            #endif
                        }
                    #endif
                #endif
                [branch]if(h > 0) {
                    bool MergedInSource = ReservoirMerge(ReservoirB[prevIndex], h, bsdf, randomNEE(129, pixel_index).x, UnifiedReservoir, 1);
                    if(MergedInSource) {
                        UnifiedWorldPos = TemporalPosition;
                        RunningWorldPos = TemporalSurface;
                    }
                }
            }
        }
    }

    int MaxM = ReSTIRGITemporalMCap;
    if(Case == 0) MaxM = max((float)MaxM * SurfaceMat.roughness, 1);
    [branch]if (UnifiedReservoir.Radiance.M > MaxM) {
        UnifiedReservoir.Radiance.Wsum *= MaxM / UnifiedReservoir.Radiance.M;
        UnifiedReservoir.Radiance.M = MaxM; 
    }

    EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPos - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);
    UnifiedReservoir.Radiance.W = clamp(UnifiedReservoir.Radiance.Wsum / max(max(UnifiedReservoir.Radiance.M, 1) * luminance(UnifiedReservoir.Radiance.Color * bsdf), 1e-7), 0, 102222000.0f);
    if(UnifiedReservoir.Radiance.W > 100 || UnifiedReservoir.Radiance.Wsum / (float)max(UnifiedReservoir.Radiance.M, 1) > 1000) UnifiedReservoir.Radiance.W = 0;

    ReservoirA[id.xy] = PackRadianceData(UnifiedReservoir.Radiance);
    ReservoirUnifiedDestinationWorldPosTemporalCurrent[id.xy] = RunningWorldPos;
    float3 NeighborNorm;
    LoadSurfaceInfo22(RunningWorldPos, PrimaryHitPosition, NeighborNorm);
    ReSTIRSecondaryDestinationWorldPos[id.xy] = uint4(asuint(UnifiedWorldPos), NeighborNorm.y == 12 ? 1 : octahedral_32(NeighborNorm));

     #ifdef ReSTIRAdvancedValidation
        if(DoReSTIRGIConnectionValidation) GradientWrite[id.xy] = (any(prevIndex >= int2(screen_width, screen_height) || prevIndex < 0)) ? 1 : Gradient[prevIndex];
    #endif




}

inline float2 vogelDiskSample(int i, int num_samples, float r_offset, float phi_offset) {
    float r = sqrt((float(i) + 0.07f + r_offset*0.93f) / float(num_samples));
    float phi = float(i) * 2.399963229728f + 2.0f * PI * phi_offset;
    float sinc;
    sincos(phi, sinc, phi);
    return r * float2(sinc,phi);
}

#pragma kernel ReSTIRGISpatial
[numthreads(KernelSize, KernelSize, 1)]
void ReSTIRGISpatial(uint3 id : SV_DispatchThreadID) {
 if(id.x >= screen_width || id.y >= screen_height) return;
    const int pixel_index = id.x + id.y * screen_width;

    const float4 GBuffer = ScreenSpaceInfoRead[id.xy];
    const int MatIndex = (asuint(GBuffer.w) << 4) >> 4;
    const uint Case = (asuint(GBuffer.w) << 1) >> 30;
    const float3 GeomNorm = i_octahedral_32(asuint(GBuffer.x));
    const float3 SurfNorm = i_octahedral_32(asuint(GBuffer.y));
    float3 PrimaryHitPosition = LoadSurfaceInfo(id.xy);
    SmallerRay CameraRay = CreateCameraRay(id.xy / float2(screen_width, screen_height) * 2.0f - 1.0f);
    [branch]if(DoPanorama) {
        float2 jitter = ((random(0, pixel_index) - 0.5));
        if(OIDNGuideWrite) jitter = 0;
        float2 uv = float2((id.xy + jitter) / float2(screen_width, screen_height));
        uv.y = 1.0f - uv.y;
        uv.x = (uv.x * (Segment.y - Segment.x)) + Segment.x;
        uv.x = 1.0f - uv.x;

        CameraRay = CreateRay(mul(CamToWorld, float4(0.0f, 0.0f, 0.0f, 1.0f)).xyz + NearPlane * normalize(equirectUvToDirection(uv)), normalize(equirectUvToDirection(uv)));
    }
    const ColData CenterCol = GlobalColors[pixel_index];
    uint MetRoughIsSpec = CenterCol.MetRoughIsSpec;
    MaterialData SurfaceMat = _Materials[MatIndex];
    const uint Flag = CenterCol.Flags;
    SurfaceMat.surfaceColor = unpackRGBE(Flag);
    SurfaceMat.roughness = FromColorSpecPacked(MetRoughIsSpec).y;
    SurfaceMat.metallic = FromColorSpecPacked(MetRoughIsSpec).x;


    float3 bsdf;
    float pdf;

    ReservoirStruct UnifiedReservoir;
    uint4 RunningWorldPos = ReservoirUnifiedDestinationWorldPosSpatialA[id.xy];
    float3 UnifiedWorldPos = asfloat(RunningWorldPos.xyz);
    float3 CannonWorldPos = UnifiedWorldPos;
    ReservoirInitialize(UnifiedReservoir);

    ReservoirStruct UnifiedReservoirSpatialPartner;
    float3 UnifiedWorldPosSpatialPartner;

    EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPos - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);

    UnpackRadianceData(ReservoirB[id.xy].xy, bsdf, UnifiedReservoir.Radiance);



#ifdef ReSTIRAdvancedValidation
    float centerValid = Gradient[id.xy];
#endif
    int K = 0;
    if(UseReSTIRGISpatial && Case != 3 && !(SurfaceMat.metallic == 1 && SurfaceMat.roughness == 0) && !(Case == 0 && SurfaceMat.roughness < 0.17)) {

        int2 CellTapCoords[6];
        float3 WorldPoses[6];
        float CorospondingWeight[6];
        float Rad = 42.0f;
        [unroll]for (int i = 0; i < 6; i++) {        
            float2 RandOffsets = randomNEE(i + 12, pixel_index);
            int2 CellOffset = vogelDiskSample(i, 6, RandOffsets.y, 2.0f * PI * RandOffsets.x) * Rad;
            if(all(CellOffset == 0)) continue;
            CellOffset *= (id.xy + CellOffset < 0 || id.xy + CellOffset >= int2(screen_width, screen_height)) ? -1 : 1;
            int2 CellTapCoord = id.xy + CellOffset;
            uint2 ScreenInfo = asuint(ScreenSpaceInfoRead[CellTapCoord].xw);
            if(ScreenInfo.y == 0 || ((asuint(ScreenInfo.y) << 1) >> 30) == 3) continue;
            if(SurfaceMat.metallic > 0 && ((ScreenInfo.y << 4) >> 4) != MatIndex) continue;
            
            float3 SampleGeomNorm = i_octahedral_32(ScreenInfo.x);
            float NormDiff = max(abs(dot(GeomNorm, SampleGeomNorm)), 0);
            
            float s = sqrt(0.05 * dot(CamPos - PrimaryHitPosition, CamPos - PrimaryHitPosition) / PI);
            float3 NeighborPos = LoadSurfaceInfo(CellTapCoord);
            float h_p = exp(-(length(PrimaryHitPosition - NeighborPos)) / s);
            float h_n = pow(NormDiff, 8);

            if(h_p * h_n <= 0.5f) {Rad /= 1.5f; continue;}
            
            #ifdef ReSTIRAdvancedValidation
                [branch]if(DoReSTIRGIConnectionValidation) {
                    float ValidityDifference = exp2(-20.0f * abs(centerValid - Gradient[CellTapCoord]));
                    if(ValidityDifference < 0.3f) {Rad /= 1.5f; continue;}
                }
            #endif

            CorospondingWeight[K] = h_p * h_n;
            WorldPoses[K] = NeighborPos;
            CellTapCoords[K++] = int2(CellTapCoord);
        }
        [loop]for (int i2 = 0; i2 < K; i2++) {
            float RandOffsets2 = randomNEESingle(i2 + 32, pixel_index);
            const uint4 PosData = ReservoirUnifiedDestinationWorldPosSpatialA[CellTapCoords[i2]];
            UnifiedWorldPosSpatialPartner = asfloat(PosData.xyz);
            float3 NeighborNorm = i_octahedral_32(PosData.w);
            bool ValidNeighbor = EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPosSpatialPartner - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);
            if(!ValidNeighbor) continue;

            float Jacobian = 1.0f;
            if(PosData.w != 1) {
                float JacobianCosNumerator = (abs(dot(NeighborNorm, normalize(UnifiedWorldPosSpatialPartner - PrimaryHitPosition))));
                float JacobianCosDenominator = (abs(dot(NeighborNorm, normalize(UnifiedWorldPosSpatialPartner - WorldPoses[i2]))));

                float JacobianLengthNumerator = dot(WorldPoses[i2] - UnifiedWorldPosSpatialPartner, WorldPoses[i2] - UnifiedWorldPosSpatialPartner);
                float JacobianLengthDenominator = dot(PrimaryHitPosition - UnifiedWorldPosSpatialPartner, PrimaryHitPosition - UnifiedWorldPosSpatialPartner);

                Jacobian = ((JacobianCosNumerator / JacobianCosDenominator)) * (JacobianLengthNumerator / JacobianLengthDenominator);
                if(Jacobian > 20 || Jacobian < 1.0f / 20.0f || isnan(Jacobian) || isinf(Jacobian)) Jacobian = 0;
            }



            bool MergedInSource = ReservoirMerge(ReservoirB[CellTapCoords[i2]], CorospondingWeight[i2] * Jacobian, bsdf, RandOffsets2, UnifiedReservoir, 1.0f);
            if(MergedInSource) {
                UnifiedWorldPos = UnifiedWorldPosSpatialPartner;
                RunningWorldPos = PosData;
            }
        }

    }


    EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPos - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);
    UnifiedReservoir.Radiance.W = clamp(UnifiedReservoir.Radiance.Wsum / max(max(UnifiedReservoir.Radiance.M, 1) * luminance(UnifiedReservoir.Radiance.Color * bsdf), 1e-7), 0, 102222000.0f);

    if(UnifiedReservoir.Radiance.W > 100 || UnifiedReservoir.Radiance.Wsum / (float)max(UnifiedReservoir.Radiance.M, 1) > 1000) UnifiedReservoir.Radiance.W = 0;

    ReservoirA[id.xy] = PackRadianceData(UnifiedReservoir.Radiance).xy;
    NEEDestinationWorldPos[id.xy] = RunningWorldPos;





}




#pragma kernel ReSTIRGISpatial2

[numthreads(KernelSize, KernelSize, 1)]
void ReSTIRGISpatial2(uint3 id : SV_DispatchThreadID) {
 if(id.x >= screen_width || id.y >= screen_height) return;
    const int pixel_index = id.x + id.y * screen_width;

    const float4 GBuffer = ScreenSpaceInfoRead[id.xy];
    const int MatIndex = (asuint(GBuffer.w) << 4) >> 4;
    const uint Case = (asuint(GBuffer.w) << 1) >> 30;
    float3 GeomNorm = i_octahedral_32(asuint(GBuffer.x));
    float3 SurfNorm = i_octahedral_32(asuint(GBuffer.y));
    float3 PrimaryHitPosition = LoadSurfaceInfo(id.xy);
    SmallerRay CameraRay = CreateCameraRay(id.xy / float2(screen_width, screen_height) * 2.0f - 1.0f);
    [branch]if(DoPanorama) {
        float2 jitter = ((random(0, pixel_index) - 0.5));
        if(OIDNGuideWrite) jitter = 0;
        float2 uv = float2((id.xy + jitter) / float2(screen_width, screen_height));
        uv.y = 1.0f - uv.y;
        uv.x = (uv.x * (Segment.y - Segment.x)) + Segment.x;
        uv.x = 1.0f - uv.x;

        CameraRay = CreateRay(mul(CamToWorld, float4(0.0f, 0.0f, 0.0f, 1.0f)).xyz + NearPlane * normalize(equirectUvToDirection(uv)), normalize(equirectUvToDirection(uv)));
    }
    const ColData CenterCol = GlobalColors[pixel_index];
    uint MetRoughIsSpec = CenterCol.MetRoughIsSpec;
    MaterialData SurfaceMat = _Materials[MatIndex];
    const uint Flag = CenterCol.Flags;
    SurfaceMat.surfaceColor = unpackRGBE(Flag);
    SurfaceMat.roughness = FromColorSpecPacked(MetRoughIsSpec).y;
    SurfaceMat.metallic = FromColorSpecPacked(MetRoughIsSpec).x;


    float3 bsdf;
    float pdf;

    ReservoirStruct UnifiedReservoir;
    float3 UnifiedWorldPos = asfloat(NEEDestinationWorldPosRead[id.xy].xyz);

    ReservoirStruct UnifiedReservoirSpatialPartner;
    float3 UnifiedWorldPosSpatialPartner;

    EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPos - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);

    UnpackRadianceData(ReservoirB[id.xy].xy, bsdf, UnifiedReservoir.Radiance);
#ifdef ReSTIRAdvancedValidation
    float centerValid = Gradient[id.xy];
#endif    
    int K = 0;
    if(UseReSTIRGISpatial && Case != 3 && !(SurfaceMat.metallic == 1 && SurfaceMat.roughness == 0) && !(Case == 0 && SurfaceMat.roughness < 0.17)) {

        int2 CellTapCoords[5];
        float3 WorldPoses[5];
        float CorospondingWeight[5];
        float Rad = 20.0f;
        [unroll]for (int i = 0; i < 5; i++) {        
            float2 RandOffsets = randomNEE(i + 48, pixel_index);
            int2 CellOffset = vogelDiskSample(i, 5, RandOffsets.y, 2.0f * PI * RandOffsets.x) * Rad;
            if(all(CellOffset == 0)) continue;
            CellOffset *= (id.xy + CellOffset < 0 || id.xy + CellOffset >= int2(screen_width, screen_height)) ? -1 : 1;
            int2 CellTapCoord = id.xy + CellOffset;
            uint2 ScreenInfo = asuint(ScreenSpaceInfoRead[CellTapCoord].xw);
            if(ScreenInfo.y == 0 || ((asuint(ScreenInfo.y) << 1) >> 30) == 3) continue;
            if(SurfaceMat.metallic > 0 && ((ScreenInfo.y << 4) >> 4) != MatIndex) continue;
            
            float3 SampleGeomNorm = i_octahedral_32(ScreenInfo.x);
            float NormDiff = max(abs(dot(GeomNorm, SampleGeomNorm)), 0);
            
            float s = sqrt(0.05 * dot(CamPos - PrimaryHitPosition, CamPos - PrimaryHitPosition) / PI);
            float3 NeighborPos = LoadSurfaceInfo(CellTapCoord);
            float h_p = exp(-(length(PrimaryHitPosition - NeighborPos)) / s);
            float h_n = pow(NormDiff, 8);

            if(h_p * h_n <= 0.5f) {Rad /= 1.5f; continue;}
            
            #ifdef ReSTIRAdvancedValidation
                [branch]if(DoReSTIRGIConnectionValidation) {
                    float ValidityDifference = exp2(-20.0f * abs(centerValid - Gradient[CellTapCoord]));
                    if(ValidityDifference < 0.3f) {Rad /= 1.5f; continue;}
                }
            #endif

            CorospondingWeight[K] = h_p * h_n;
            WorldPoses[K] = h_p * h_n;
            CellTapCoords[K++] = int2(CellTapCoord);
        }
        [loop]for (int i2 = 0; i2 < K; i2++) {
            int2 CellTapCoord = CellTapCoords[i2];
            float2 RandOffsets2 = randomNEE(i2 + 64, pixel_index);
            uint4 PosData = NEEDestinationWorldPosRead[CellTapCoord];
            UnifiedWorldPosSpatialPartner = asfloat(PosData.xyz);
            float3 NeighborNorm = i_octahedral_32(PosData.w);
            bool ValidNeighbor = EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPosSpatialPartner - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);
            if(!ValidNeighbor) continue;

            float Jacobian = 1.0f;
            if(PosData.w != 1) {
                float JacobianCosNumerator = (abs(dot(NeighborNorm, normalize(UnifiedWorldPosSpatialPartner - PrimaryHitPosition))));
                float JacobianCosDenominator = (abs(dot(NeighborNorm, normalize(UnifiedWorldPosSpatialPartner - WorldPoses[i2]))));

                float JacobianLengthNumerator = dot(WorldPoses[i2] - UnifiedWorldPosSpatialPartner, WorldPoses[i2] - UnifiedWorldPosSpatialPartner);
                float JacobianLengthDenominator = dot(PrimaryHitPosition - UnifiedWorldPosSpatialPartner, PrimaryHitPosition - UnifiedWorldPosSpatialPartner);

                Jacobian = ((JacobianCosNumerator / JacobianCosDenominator)) * (JacobianLengthNumerator / JacobianLengthDenominator);
                if(Jacobian > 20.0f || Jacobian < 1.0f / 20.0f || isnan(Jacobian) || isinf(Jacobian)) Jacobian = 0;
            }


            bool MergedInSource = ReservoirMerge(ReservoirB[CellTapCoord], CorospondingWeight[i2] * Jacobian, bsdf, RandOffsets2.x, UnifiedReservoir, 1.0f);
            if(MergedInSource) {
                UnifiedWorldPos = UnifiedWorldPosSpatialPartner;
            }
        }

    }



   [branch]if (DoReSTIRGIConnectionValidation) {
        float DistDist = 1;
        if(SurfaceMat.specTrans == 0) {
            SmallerRay ray = CreateRay(PrimaryHitPosition, normalize(UnifiedWorldPos - PrimaryHitPosition));
            bool FlippedGeomnorm = (SurfaceMat.diffTrans != 0 && dot(ray.direction, GeomNorm) <= 0);
            if(FlippedGeomnorm) GeomNorm *= -1.0f;
            if(FlippedGeomnorm) SurfNorm *= -1.0f;
            PrimaryHitPosition += GeomNorm * NormalOffset;
            ray = CreateRay(PrimaryHitPosition, normalize(UnifiedWorldPos - PrimaryHitPosition));

            float Distance = length(PrimaryHitPosition - UnifiedWorldPos) - 0.025f;
            [branch]if (luminance(UnifiedReservoir.Radiance.Color) != 0) {
                if(dot(ray.direction, SurfNorm) <= 0) {
                // if(dot(ray.direction, GeomNorm) <= 0) {
                    UnifiedReservoir.Radiance.Wsum = 0;
                    UnifiedReservoir.Radiance.M = 0;
                    DistDist = 0;
                } else {
                #ifdef ReSTIRAdvancedValidation
                    float TargDist = VisabilityCheck(ray, Distance);
                    if (TargDist != Distance) {
                        DistDist = exp(-abs(Distance - TargDist));
                #else
                    if(!VisabilityCheck(ray, Distance)) {
                #endif
                        UnifiedReservoir.Radiance.Wsum = 0;
                        UnifiedReservoir.Radiance.M = 0;
                        #ifdef ReSTIRShadowBorderImprovement
                            UnifiedWorldPos = LoadSurfaceInfo23(BackupReservoirWorldPos[id.xy], PrimaryHitPosition-GeomNorm * NormalOffset);
                            EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPos - (PrimaryHitPosition-GeomNorm * NormalOffset)), SurfNorm, pdf, bsdf, pixel_index);
                            UnpackRadianceData(BackupReservoir[id.xy], bsdf, UnifiedReservoir.Radiance);
                            UnifiedReservoir.Radiance.Wsum /= (float)UnifiedReservoir.Radiance.M;
                            UnifiedReservoir.Radiance.M = 2;
                        #endif
                    }
                }
            }
            PrimaryHitPosition -= GeomNorm * NormalOffset;
            if(FlippedGeomnorm) GeomNorm *= -1.0f;
            if(FlippedGeomnorm) SurfNorm *= -1.0f;
        }

        #ifdef ReSTIRAdvancedValidation
            GradientWrite[id.xy] = DistDist;
        #endif

    }


    EvaluateBsdf(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPos - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);
    UnifiedReservoir.Radiance.W = clamp(UnifiedReservoir.Radiance.Wsum / max(max(UnifiedReservoir.Radiance.M, 1) * luminance(UnifiedReservoir.Radiance.Color * bsdf), 1e-7), 0, 10000.0f);

    if(UnifiedReservoir.Radiance.W > 100 || UnifiedReservoir.Radiance.Wsum / (float)max(UnifiedReservoir.Radiance.M, 1) > 1000) UnifiedReservoir.Radiance.W = 0;

    // if(id.x > screen_width / 2) EvaluateBsdf22(SurfaceMat, CameraRay.direction, normalize(UnifiedWorldPos - PrimaryHitPosition), SurfNorm, pdf, bsdf, pixel_index);




    if(Case != 3 && !(Case == 0 && SurfaceMat.roughness < 0.01)) {
        GlobalColors[pixel_index].PrimaryNEERay = packRGBE(pow(float3(0,0,0),rcp(2.2f)));

        GlobalColors[pixel_index].Indirect = 0;
        GlobalColors[pixel_index].Direct = UnifiedReservoir.Radiance.Color * UnifiedReservoir.Radiance.W;
        if(GetBounceData(GlobalColors[pixel_index].MetRoughIsSpec) != 1) {
            SmallerRay ray = CreateRay(PrimaryHitPosition, normalize(UnifiedWorldPos - PrimaryHitPosition));
            if(GetFlag(SurfaceMat.Tag, Thin) && dot(GeomNorm, ray.direction) < 0 && Case == 2) bsdf *= sqrt(exp(-CalculateExtinction(SurfaceMat.transmittanceColor, SurfaceMat.scatterDistance == 0.0f ? 1.0f : SurfaceMat.scatterDistance)));
            GlobalColors[pixel_index].Data.xyz = bsdf;
        }
    } else {
        GlobalColors[pixel_index].Direct = GlobalColors[pixel_index].Direct + GlobalColors[pixel_index].Indirect + pow(unpackRGBE(CenterCol.PrimaryNEERay),2.2f);
        GlobalColors[pixel_index].PrimaryNEERay = packRGBE(pow(float3(0,0,0),rcp(2.2f)));

        GlobalColors[pixel_index].Indirect = 0;
    }

}












